a = int(input("Input a:"))
b = int(input("Input b:"))

print("a + b =", a+b)
print("a - b =", a-b)
print("a * b =", a*b)
print("a / b =", a/b)
print("a ** b =", a**b)
print("a // b =", a//b)
print("a % b =", a%b)
