a = float(input('Уведіть число А:'))
b = float(input('Уведіть число B:'))
print(f'A+B={a + b}')
print(f'A-B={a - b}')
print(f'A*B={a * b}')
print(f'A**B={a ** b}')
print(f'A//B={a // b}')
print(f'A%B={a % b}')