num_a = int (input ("Enter first number " ))
num_b = int ( input("Enter second number " ))
print ("THANKS")
print ("А + Б = ", num_a + num_b )
print ("А - Б = ", num_a - num_b )
print ("А * Б = ", num_a * num_b )
print ("А / Б = ", num_a / num_b )
print ("А ** Б = ", num_a ** num_b )
print ("А // Б = ", num_a // num_b )
print ("А % Б = ", num_a % num_b )