user_name = input("What is yor name?\n")
print(f"Hello, {user_name}!")
age = input("How old are you?\n")
print(f"Your age is {age}.")
city = input("Where do you live?\n")
print(f"You live in {city}.")
